/**
 * Boss直聘 (BOSS Zhipin) Platform Executor — Passthrough + Conversation Pipeline
 *
 * Anti-scraping: EXTREME | Session: cookie (__zp_stoken__) | Headless: No
 * Apply method: chat_initiate (打招呼) | Pipeline: passthrough + conversation
 * Daily budget: 10 greetings, 5 messages | Delays: 3-8s
 *
 * CRITICAL: Boss直聘 has NO "投递" button. The primary action is "立即沟通" (greet).
 * The 投递专员 agent does NOT handle Boss. The 招聘关系经理 is the primary executor.
 *
 * Source: PLATFORM_RULE_AND_AGENT_SPEC.md § Boss直聘
 *         MULTI_PLATFORM_PIPELINE_SPEC.md § 6.2
 */

import { createContext, randomDelay } from '../utils/browser-pool.js';
import type { Page } from 'playwright';

const DELAY = { page: [3000, 8000] as const, click: [1500, 3000] as const };

type BossJob = {
  job_title: string;
  company_name: string;
  location_label: string;
  salary_text?: string;
  job_description_url: string;
  job_description_text: string;
  external_ref: string;
};

type BossMessage = {
  threadId: string;
  senderName: string;
  messageText: string;
  receivedAt: string;
};

/**
 * Discover jobs via Boss直聘 keyword search.
 * URL: https://www.zhipin.com/web/geek/job?query=xxx&city=xxx
 *
 * WARNING: Boss has extreme anti-scraping. __zp_stoken__ is an encrypted cookie
 * generated by obfuscated client-side JS. Expect frequent CAPTCHA interruptions.
 */
export async function discoverBossJobs(params: {
  sessionCookies: string;
  keywords: string[];
  city?: string;
  limit?: number;
}): Promise<BossJob[]> {
  const limit = params.limit ?? 10;
  const context = await createContext({ cookies: params.sessionCookies });
  const page = await context.newPage();

  try {
    const keyword = params.keywords.join(' ');
    const searchUrl = `https://www.zhipin.com/web/geek/job?query=${encodeURIComponent(keyword)}${params.city ? `&city=${encodeURIComponent(params.city)}` : ''}`;

    await page.goto(searchUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await randomDelay(DELAY.page[0], DELAY.page[1]);

    // Check for security challenge / login redirect
    if (isLoginPage(page) || await isSecurityChallenge(page)) {
      console.warn('[boss] Session expired or security challenge');
      return [];
    }

    const jobs: BossJob[] = [];
    const cards = page.locator('.job-card-wrapper, .job-card-body, .search-job-result .job-card-box');
    const count = Math.min(await cards.count(), limit);

    for (let i = 0; i < count; i++) {
      try {
        const card = cards.nth(i);
        await card.scrollIntoViewIfNeeded();
        await randomDelay(500, 1500); // Extra delay for Boss anti-scraping

        const title = await card.locator('.job-name, .job-title').first().textContent() || '';
        const company = await card.locator('.company-name a, .company-name').first().textContent() || '';
        const location = await card.locator('.job-area, .job-area-wrapper').first().textContent() || '';
        const salary = await card.locator('.salary, .job-limit .red').first().textContent().catch(() => '') || '';

        const linkEl = card.locator('a[href*="/job_detail/"], a[ka="search_list_job"]').first();
        const href = await linkEl.getAttribute('href') || '';

        // Boss job IDs are in URL path: /job_detail/xxxxx.html
        const jobId = href.match(/job_detail\/([^.]+)/)?.[1] || `boss-${i}`;

        if (title.trim()) {
          jobs.push({
            job_title: title.trim(),
            company_name: company.trim(),
            location_label: location.trim(),
            salary_text: salary.trim() || undefined,
            job_description_url: href.startsWith('http') ? href : `https://www.zhipin.com${href}`,
            job_description_text: '',
            external_ref: `boss:${jobId}`,
          });
        }
      } catch { /* skip card */ }
    }

    // Load JD for top results (fewer than other platforms due to anti-scraping)
    for (const job of jobs.slice(0, 3)) {
      try {
        await page.goto(job.job_description_url, { waitUntil: 'domcontentloaded', timeout: 20000 });
        await randomDelay(DELAY.page[0], DELAY.page[1]);

        if (await isSecurityChallenge(page)) {
          console.warn('[boss] Security challenge on job detail, stopping JD fetch');
          break;
        }

        const jd = await page.locator('.job-sec-text, .job-detail-section .text, .job-detail .detail-content').first().textContent();
        job.job_description_text = jd?.trim() || '';
      } catch { /* skip detail */ }
    }

    return jobs;

  } catch (err) {
    console.error(`[boss] Discovery error: ${err instanceof Error ? err.message : err}`);
    return [];
  } finally {
    await page.close();
    await context.close();
  }
}

/**
 * Send greeting message (打招呼) to a Boss直聘 job posting.
 * This is Boss's equivalent of "apply" — there is no traditional submit button.
 *
 * Flow: Navigate job detail → click "立即沟通" → type greeting → send
 */
export async function sendBossGreeting(params: {
  sessionCookies: string;
  jobDetailUrl: string;
  greetingText: string;
}): Promise<{
  outcome: 'success' | 'soft_failure' | 'hard_failure';
  confirmationSignal?: string;
  errorMessage?: string;
}> {
  const context = await createContext({ cookies: params.sessionCookies });
  const page = await context.newPage();

  try {
    await page.goto(params.jobDetailUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await randomDelay(DELAY.page[0], DELAY.page[1]);

    if (isLoginPage(page)) {
      return { outcome: 'hard_failure', errorMessage: 'Session expired' };
    }

    if (await isSecurityChallenge(page)) {
      return { outcome: 'hard_failure', errorMessage: 'Security challenge (CAPTCHA)' };
    }

    // Check if already greeted (已沟通)
    const pageText = await page.textContent('body') || '';
    if (/已沟通|继续沟通/.test(pageText)) {
      return { outcome: 'soft_failure', errorMessage: 'Already greeted (已沟通)' };
    }

    // Click "立即沟通" button
    const greetBtn = page.locator('a:has-text("立即沟通"), button:has-text("立即沟通"), .btn-startchat').first();
    if (!(await greetBtn.isVisible({ timeout: 5000 }).catch(() => false))) {
      return { outcome: 'soft_failure', errorMessage: '立即沟通 button not found' };
    }

    await greetBtn.click();
    await randomDelay(DELAY.page[0], DELAY.page[1]);

    // After clicking, Boss opens a chat dialog or navigates to chat page
    // Look for the message input area
    const chatInput = page.locator('.chat-input textarea, .chat-input [contenteditable], .message-input textarea, [class*="chat"] textarea').first();
    if (!(await chatInput.isVisible({ timeout: 8000 }).catch(() => false))) {
      // Some positions go directly to chat page
      const chatUrl = page.url();
      if (chatUrl.includes('/web/geek/chat')) {
        // Already on chat page, find input
        const chatPageInput = page.locator('textarea, [contenteditable="true"]').first();
        if (await chatPageInput.isVisible({ timeout: 5000 }).catch(() => false)) {
          await chatPageInput.fill(params.greetingText);
          await randomDelay(DELAY.click[0], DELAY.click[1]);

          const sendBtn = page.locator('button:has-text("发送"), .btn-send').first();
          if (await sendBtn.isVisible().catch(() => false)) {
            await sendBtn.click();
            await randomDelay(DELAY.click[0], DELAY.click[1]);
            return { outcome: 'success', confirmationSignal: 'Message sent on chat page' };
          }
        }
      }
      return { outcome: 'soft_failure', errorMessage: 'Chat input not found after clicking 立即沟通' };
    }

    // Type and send greeting message
    await chatInput.fill(params.greetingText);
    await randomDelay(DELAY.click[0], DELAY.click[1]);

    const sendBtn = page.locator('button:has-text("发送"), .btn-send, [class*="send"]').first();
    if (await sendBtn.isVisible().catch(() => false)) {
      await sendBtn.click();
      await randomDelay(DELAY.click[0], DELAY.click[1]);
    } else {
      // Try Enter key as fallback
      await chatInput.press('Enter');
      await randomDelay(DELAY.click[0], DELAY.click[1]);
    }

    return { outcome: 'success', confirmationSignal: 'Greeting message sent' };

  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    console.error(`[boss] Greeting error: ${msg}`);
    return { outcome: 'soft_failure', errorMessage: msg };

  } finally {
    await page.close();
    await context.close();
  }
}

/**
 * Poll Boss直聘 inbox for new messages.
 * Visits the chat page and scrapes recent conversations.
 */
export async function pollBossMessages(params: {
  sessionCookies: string;
}): Promise<BossMessage[]> {
  const context = await createContext({ cookies: params.sessionCookies });
  const page = await context.newPage();

  try {
    await page.goto('https://www.zhipin.com/web/geek/chat', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await randomDelay(DELAY.page[0], DELAY.page[1]);

    if (isLoginPage(page) || await isSecurityChallenge(page)) {
      console.warn('[boss] Session expired or security challenge during message poll');
      return [];
    }

    const messages: BossMessage[] = [];

    // Get conversation list items
    const convItems = page.locator('.chat-item, .conversation-item, [class*="chat-list"] li');
    const convCount = Math.min(await convItems.count(), 10);

    for (let i = 0; i < convCount; i++) {
      try {
        const item = convItems.nth(i);

        const senderName = await item.locator('.name, .title-name').first().textContent() || '';
        const lastMsg = await item.locator('.last-msg, .msg-text, .last-message').first().textContent() || '';
        const timeText = await item.locator('.time, .date, .msg-time').first().textContent() || '';

        // Extract thread ID from data attributes or click behavior
        const threadLink = await item.locator('a').first().getAttribute('href').catch(() => '');
        const threadId = threadLink?.match(/id=(\w+)/)?.[1] || `boss-thread-${i}`;

        if (senderName.trim() && lastMsg.trim()) {
          messages.push({
            threadId,
            senderName: senderName.trim(),
            messageText: lastMsg.trim(),
            receivedAt: new Date().toISOString(), // Boss doesn't always show precise timestamps
          });
        }
      } catch { /* skip conversation item */ }
    }

    return messages;

  } catch (err) {
    console.error(`[boss] Message poll error: ${err instanceof Error ? err.message : err}`);
    return [];
  } finally {
    await page.close();
    await context.close();
  }
}

/**
 * Send a reply message in an existing Boss直聘 conversation.
 * Used for follow-up messages in Loop 2.
 */
export async function sendBossReply(params: {
  sessionCookies: string;
  threadUrl: string;
  messageText: string;
}): Promise<{
  outcome: 'success' | 'soft_failure' | 'hard_failure';
  errorMessage?: string;
}> {
  const context = await createContext({ cookies: params.sessionCookies });
  const page = await context.newPage();

  try {
    await page.goto(params.threadUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await randomDelay(DELAY.page[0], DELAY.page[1]);

    if (isLoginPage(page)) {
      return { outcome: 'hard_failure', errorMessage: 'Session expired' };
    }

    const chatInput = page.locator('textarea, [contenteditable="true"]').first();
    if (!(await chatInput.isVisible({ timeout: 5000 }).catch(() => false))) {
      return { outcome: 'soft_failure', errorMessage: 'Chat input not found' };
    }

    await chatInput.fill(params.messageText);
    await randomDelay(DELAY.click[0], DELAY.click[1]);

    const sendBtn = page.locator('button:has-text("发送"), .btn-send').first();
    if (await sendBtn.isVisible().catch(() => false)) {
      await sendBtn.click();
    } else {
      await chatInput.press('Enter');
    }

    await randomDelay(DELAY.click[0], DELAY.click[1]);
    return { outcome: 'success' };

  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    console.error(`[boss] Reply error: ${msg}`);
    return { outcome: 'soft_failure', errorMessage: msg };

  } finally {
    await page.close();
    await context.close();
  }
}

/**
 * Capability-level health check.
 * Boss has the shortest session TTL (~2-4h), so this runs every 15 min.
 */
export async function checkBossCapabilityHealth(params: {
  sessionCookies: string;
}): Promise<Record<string, 'healthy' | 'degraded' | 'blocked' | 'unknown'>> {
  const context = await createContext({ cookies: params.sessionCookies });
  const page = await context.newPage();
  const caps: Record<string, 'healthy' | 'degraded' | 'blocked' | 'unknown'> = {
    search: 'unknown', detail: 'unknown', chat: 'unknown', resume: 'unknown',
  };

  try {
    // Probe search
    await page.goto('https://www.zhipin.com/web/geek/job?query=test', { waitUntil: 'domcontentloaded', timeout: 15000 });

    if (isLoginPage(page)) {
      caps.search = 'blocked';
      return caps;
    }

    if (await isSecurityChallenge(page)) {
      caps.search = 'blocked';
      return caps;
    }

    caps.search = 'healthy';

    // Probe chat page
    await page.goto('https://www.zhipin.com/web/geek/chat', { waitUntil: 'domcontentloaded', timeout: 15000 });
    if (!isLoginPage(page) && !(await isSecurityChallenge(page))) {
      caps.chat = 'healthy';
    } else {
      caps.chat = 'blocked';
    }

  } catch {
    // Leave as unknown
  } finally {
    await page.close();
    await context.close();
  }

  return caps;
}

function isLoginPage(page: Page): boolean {
  const url = page.url();
  return url.includes('/login') || url.includes('/web/user/');
}

async function isSecurityChallenge(page: Page): Promise<boolean> {
  // Boss shows a security page with sliding captcha or verification
  const url = page.url();
  if (url.includes('/safe/') || url.includes('/verify')) return true;

  const hasSlider = await page.locator('.slider-verify, .geetest_slider, .captcha-container, #nc_1_wrapper').first().isVisible({ timeout: 2000 }).catch(() => false);
  return hasSlider;
}
