-- M0: Execution Entities
-- Opportunity, Material, SubmissionAttempt, Handoff

CREATE TABLE opportunity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES team(id),
  stage opportunity_stage NOT NULL DEFAULT 'discovered',
  previous_stage opportunity_stage,
  stage_changed_at timestamptz NOT NULL DEFAULT now(),
  company_name text NOT NULL,
  job_title text NOT NULL,
  location_label text,
  job_description_url text,
  job_description_text text,
  company_summary text,
  source_platform_id uuid NOT NULL REFERENCES platform_definition(id),
  external_ref text,
  source_freshness freshness NOT NULL DEFAULT 'unknown',
  canonical_group_id uuid,
  fit_posture fit_posture,
  fit_reason_tags jsonb DEFAULT '[]'::jsonb,
  recommendation recommendation_verdict,
  recommendation_reason_tags jsonb DEFAULT '[]'::jsonb,
  recommendation_next_step_hint text,
  priority_level priority NOT NULL DEFAULT 'medium',
  lead_agent_id uuid REFERENCES agent_instance(id),
  requires_takeover boolean NOT NULL DEFAULT false,
  closure_reason opportunity_closure_reason,
  closed_at timestamptz,
  why_selected_summary text,
  risk_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  next_step_summary text,
  current_owner_type text NOT NULL DEFAULT 'team',
  latest_event_at timestamptz,
  latest_event_summary text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE material (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES team(id),
  opportunity_id uuid REFERENCES opportunity(id),
  material_type material_type NOT NULL,
  status material_status NOT NULL DEFAULT 'generating',
  language language_code NOT NULL DEFAULT 'en',
  storage_path text,
  content_text text,
  source_profile_baseline_id uuid REFERENCES profile_baseline(id),
  source_resume_asset_id uuid REFERENCES resume_asset(id),
  edit_intensity edit_intensity,
  preservation_mode preservation_mode,
  version integer NOT NULL DEFAULT 1,
  superseded_by_id uuid REFERENCES material(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE submission_attempt (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES team(id),
  opportunity_id uuid NOT NULL REFERENCES opportunity(id),
  platform_connection_id uuid NOT NULL REFERENCES platform_connection(id),
  agent_task_id uuid,
  attempt_number integer NOT NULL DEFAULT 1,
  execution_outcome execution_outcome NOT NULL,
  failure_reason_code text,
  failure_reason_message text,
  platform_response_hint text,
  next_stage_hint text,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE handoff (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES team(id),
  opportunity_id uuid NOT NULL REFERENCES opportunity(id),
  handoff_type handoff_type NOT NULL,
  state handoff_state NOT NULL DEFAULT 'awaiting_takeover',
  urgency urgency NOT NULL DEFAULT 'medium',
  source_agent_id uuid REFERENCES agent_instance(id),
  source_agent_role_code agent_role_code,
  handoff_reason text NOT NULL,
  context_summary text NOT NULL,
  explanation_text text,
  suggested_next_action text,
  suggested_reply_text text,
  risk_notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  due_at timestamptz,
  takeover_started_at timestamptz,
  resolved_at timestamptz,
  returned_at timestamptz,
  closed_at timestamptz,
  resolution_type handoff_resolution_type,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
